import 'package:flutter/material.dart';
import 'dart:typed_data';
import 'package:file_picker/file_picker.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../models/channel_model.dart';
import '../models/channel_post_model.dart';
import '../services/channel_service.dart';
import '../services/firebase_data_service.dart';
import '../widgets/media_preview_widget.dart';

class ChannelPostsScreen extends StatefulWidget {
  final ChannelModel channel;

  const ChannelPostsScreen({super.key, required this.channel});

  @override
  State<ChannelPostsScreen> createState() => _ChannelPostsScreenState();
}

class _ChannelPostsScreenState extends State<ChannelPostsScreen> {
  final _formKey = GlobalKey<FormState>();
  final _textController = TextEditingController();
  final _linkUrlController = TextEditingController();

  // For file upload
  Uint8List? _fileBytes;
  String? _fileName;
  bool _isUploading = false;
  
  // For audio rooms
  List<Map<String, dynamic>> _audioRooms = [];
  String? _selectedRoomId;
  String? _selectedRoomName;
  bool _isLoadingRooms = false;

  @override
  void initState() {
    super.initState();
    _fetchAudioRooms();
  }

  Future<void> _fetchAudioRooms() async {
    setState(() => _isLoadingRooms = true);
    try {
      final rooms = await FirebaseDataService.getAllAudioRooms();
      setState(() {
        _audioRooms = rooms;
      });
    } catch (e) {
      debugPrint('Error fetching rooms: $e');
    } finally {
      setState(() => _isLoadingRooms = false);
    }
  }

  @override
  void dispose() {
    _textController.dispose();
    _linkUrlController.dispose();
    super.dispose();
  }

  void _resetForm() {
    _textController.clear();
    _linkUrlController.clear();
    _fileBytes = null;
    _fileName = null;
    _selectedRoomId = null;
    _selectedRoomName = null;
    _isUploading = false;
  }

  Future<void> _pickFile(StateSetter setStateDialog) async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['png', 'jpg', 'jpeg', 'gif'],
        withData: true,
      );

      if (result != null && result.files.isNotEmpty) {
        setStateDialog(() {
          _fileBytes = result.files.first.bytes;
          _fileName = result.files.first.name;
        });
      }
    } catch (e) {
      debugPrint('Error picking file: $e');
    }
  }

  Future<String?> _uploadToStorage(Uint8List bytes, String name) async {
    try {
      final storageName = 'official_channels/posts/${DateTime.now().millisecondsSinceEpoch}_$name';
      final ref = FirebaseStorage.instance.ref().child(storageName);
      final uploadTask = await ref.putData(bytes);
      return await uploadTask.ref.getDownloadURL();
    } catch (e) {
      debugPrint('Error uploading file: $e');
      return null;
    }
  }

  Future<void> _submitPost(StateSetter setStateDialog) async {
    if (!_formKey.currentState!.validate()) return;
    
    if (_textController.text.isEmpty && 
        _fileBytes == null && 
        _linkUrlController.text.isEmpty && 
        _selectedRoomId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please provide at least one piece of content (text, image, link, or room ID)')));
      return;
    }

    setStateDialog(() => _isUploading = true);

    try {
      String? uploadedImageUrl;

      if (_fileBytes != null && _fileName != null) {
        uploadedImageUrl = await _uploadToStorage(_fileBytes!, _fileName!);
        if (uploadedImageUrl == null) {
          throw Exception('Failed to upload image');
        }
      }

      final post = ChannelPostModel(
        id: '', // Generated by Firestore
        channelId: widget.channel.id,
        textContent: _textController.text.isEmpty ? null : _textController.text,
        imageUrl: uploadedImageUrl,
        linkUrl: _linkUrlController.text.isEmpty ? null : _linkUrlController.text,
        voiceRoomId: _selectedRoomId,
        createdAt: DateTime.now(),
      );

      await ChannelService.createPost(post);
      
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Post created successfully')));
        Navigator.pop(context);
        _resetForm();
      }
    } catch (e) {
      setStateDialog(() => _isUploading = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('Error: ${e.toString()}')));
      }
    }
  }

  void _showAddPostDialog(BuildContext context) {
    showDialog(
      context: context,
      barrierDismissible: !_isUploading,
      builder: (context) => StatefulBuilder(
        builder: (context, setStateDialog) {
          return AlertDialog(
            backgroundColor: Colors.grey[900],
            title: const Text('Create New Post', style: TextStyle(color: Colors.white)),
            content: SingleChildScrollView(
              child: Form(
                key: _formKey,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    TextFormField(
                      controller: _textController,
                      style: const TextStyle(color: Colors.white),
                      decoration: InputDecoration(
                        labelText: 'Message Text',
                        labelStyle: TextStyle(color: Colors.grey[400]),
                        enabledBorder: const UnderlineInputBorder(borderSide: BorderSide(color: Colors.grey)),
                      ),
                      maxLines: 3,
                      enabled: !_isUploading,
                    ),
                    const SizedBox(height: 24),
                    
                    Text('Post Image', style: TextStyle(color: Colors.grey[400], fontSize: 12)),
                    const SizedBox(height: 8),
                    GestureDetector(
                      onTap: _isUploading
                          ? null
                          : () async {
                              await _pickFile(setStateDialog);
                            },
                      child: Container(
                        height: 120,
                        width: double.infinity,
                        decoration: BoxDecoration(
                          color: Colors.grey[800],
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: Colors.grey[600]!),
                        ),
                        child: _fileBytes != null
                            ? ClipRRect(
                                borderRadius: BorderRadius.circular(12),
                                child: Image.memory(_fileBytes!, fit: BoxFit.cover),
                              )
                            : Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  const Icon(Icons.add_photo_alternate, color: Colors.blue, size: 40),
                                  const SizedBox(height: 8),
                                  Text(
                                    'Tap to select Image',
                                    style: TextStyle(color: Colors.grey[400]),
                                  ),
                                ],
                              ),
                      ),
                    ),
                    if (_fileBytes != null) ...[
                      const SizedBox(height: 8),
                      Align(
                        alignment: Alignment.centerRight,
                        child: TextButton(
                          onPressed: _isUploading ? null : () {
                            setStateDialog(() {
                              _fileBytes = null;
                              _fileName = null;
                            });
                          },
                          child: const Text('Remove Image', style: TextStyle(color: Colors.red)),
                        ),
                      )
                    ],
                    
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _linkUrlController,
                      style: const TextStyle(color: Colors.white),
                      decoration: InputDecoration(
                        labelText: 'Link URL (Optional)',
                        labelStyle: TextStyle(color: Colors.grey[400]),
                        enabledBorder: const UnderlineInputBorder(borderSide: BorderSide(color: Colors.grey)),
                      ),
                      enabled: !_isUploading,
                    ),
                    
                    const SizedBox(height: 24),
                    Text('Share Voice Room', style: TextStyle(color: Colors.grey[400], fontSize: 12)),
                    const SizedBox(height: 8),
                    _isLoadingRooms 
                        ? const Center(child: CircularProgressIndicator(color: Colors.blue))
                        : Autocomplete<Map<String, dynamic>>(
                            optionsBuilder: (TextEditingValue textEditingValue) {
                              if (textEditingValue.text.isEmpty) {
                                return const Iterable<Map<String, dynamic>>.empty();
                              }
                              return _audioRooms.where((room) {
                                final name = (room['roomName'] ?? '').toString().toLowerCase();
                                final id = (room['roomId'] ?? room['id'] ?? '').toString().toLowerCase();
                                final query = textEditingValue.text.toLowerCase();
                                return name.contains(query) || id.contains(query);
                              });
                            },
                            displayStringForOption: (Map<String, dynamic> option) => 
                                '${option['roomName']} (${option['roomId'] ?? option['id']})',
                            onSelected: (Map<String, dynamic> selection) {
                              setStateDialog(() {
                                _selectedRoomId = (selection['roomId'] ?? selection['id']).toString();
                                _selectedRoomName = selection['roomName'];
                              });
                            },
                            fieldViewBuilder: (context, controller, focusNode, onFieldSubmitted) {
                              return TextFormField(
                                controller: controller,
                                focusNode: focusNode,
                                style: const TextStyle(color: Colors.white),
                                decoration: InputDecoration(
                                  hintText: 'Search by Room Name or ID',
                                  hintStyle: TextStyle(color: Colors.grey[600]),
                                  filled: true,
                                  fillColor: Colors.grey[800],
                                  border: OutlineInputBorder(
                                    borderRadius: BorderRadius.circular(8),
                                    borderSide: BorderSide.none,
                                  ),
                                  suffixIcon: const Icon(Icons.search, color: Colors.grey),
                                ),
                                enabled: !_isUploading,
                              );
                            },
                          ),
                    if (_selectedRoomId != null) ...[
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          Icon(Icons.check_circle, color: Colors.green[400], size: 16),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              'Selected: $_selectedRoomName ($_selectedRoomId)',
                              style: const TextStyle(color: Colors.white),
                            ),
                          ),
                          IconButton(
                            icon: const Icon(Icons.close, color: Colors.red, size: 16),
                            onPressed: _isUploading ? null : () {
                              setStateDialog(() {
                                _selectedRoomId = null;
                                _selectedRoomName = null;
                              });
                            },
                          )
                        ],
                      )
                    ],

                    if (_isUploading) ...[
                      const SizedBox(height: 24),
                      const Center(child: CircularProgressIndicator(color: Colors.blue)),
                      const SizedBox(height: 8),
                      const Center(child: Text('Uploading and saving...', style: TextStyle(color: Colors.grey))),
                    ]
                  ],
                ),
              ),
            ),
          actions: [
            TextButton(
              onPressed: _isUploading ? null : () {
                Navigator.pop(context);
                _resetForm();
              },
              child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
            ),
            ElevatedButton(
              onPressed: _isUploading ? null : () => _submitPost(setStateDialog),
              style: ElevatedButton.styleFrom(backgroundColor: Colors.blue),
              child: const Text('Post'),
            ),
          ],
        );
      }
    ),
    ).then((_) => _resetForm());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        title: Text('${widget.channel.name} Posts'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showAddPostDialog(context),
        backgroundColor: Colors.blue,
        child: const Icon(Icons.add),
      ),
      body: StreamBuilder<List<ChannelPostModel>>(
        stream: ChannelService.getChannelPostsStream(widget.channel.id),
        builder: (context, snapshot) {
          if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}', style: const TextStyle(color: Colors.red)));
          }

          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator(color: Colors.blue));
          }

          final posts = snapshot.data ?? [];

          if (posts.isEmpty) {
            return const Center(
              child: Text('No posts yet.', style: TextStyle(color: Colors.grey)),
            );
          }

          return ListView.builder(
            itemCount: posts.length,
            itemBuilder: (context, index) {
              final post = posts[index];
              return Card(
                color: Colors.grey[900],
                margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
                child: Padding(
                  padding: const EdgeInsets.all(16),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            'Posted: ${post.createdAt.toLocal().toString().split('.')[0]}',
                            style: TextStyle(color: Colors.grey[500], fontSize: 12),
                          ),
                          IconButton(
                            icon: const Icon(Icons.delete, color: Colors.red, size: 20),
                            onPressed: () {
                              ChannelService.deletePost(post.id);
                            },
                          )
                        ],
                      ),
                      const SizedBox(height: 8),
                      if (post.textContent != null && post.textContent!.isNotEmpty) ...[
                        Text(post.textContent!, style: const TextStyle(color: Colors.white, fontSize: 16)),
                        const SizedBox(height: 8),
                      ],
                      if (post.imageUrl != null && post.imageUrl!.isNotEmpty) ...[
                        MediaPreviewWidget(
                          url: post.imageUrl!,
                          width: double.infinity,
                          height: 200, // Or whatever height makes sense, maybe remove fixed height, but MediaPreviewWidget requires fixed size. Let's just use 200.
                        ),
                        const SizedBox(height: 8),
                      ],
                      if (post.linkUrl != null && post.linkUrl!.isNotEmpty) ...[
                        Row(
                          children: [
                            const Icon(Icons.link, color: Colors.blue),
                            const SizedBox(width: 8),
                            Expanded(child: Text(post.linkUrl!, style: const TextStyle(color: Colors.blue))),
                          ],
                        ),
                        const SizedBox(height: 8),
                      ],
                      if (post.voiceRoomId != null && post.voiceRoomId!.isNotEmpty) ...[
                        Container(
                          padding: const EdgeInsets.all(12),
                          decoration: BoxDecoration(
                            color: Colors.purple.withValues(alpha: 0.2),
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(color: Colors.purple),
                          ),
                          child: Row(
                            children: [
                              const Icon(Icons.headset_mic, color: Colors.purple),
                              const SizedBox(width: 12),
                              Text('Join Room ID: ${post.voiceRoomId}', style: const TextStyle(color: Colors.purple, fontWeight: FontWeight.bold)),
                            ],
                          ),
                        ),
                      ],
                    ],
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
